FROM --platform=linux/amd64 node:22@sha256:dcf06103a9d4087e3244a51697adbbb85331dcb7161dbe994ca1cd07dd32e2a5
ENV LANG=en_US.UTF-8
ENV PPTRUSER_UID=10042
ENV DBUS_SESSION_BUS_ADDRESS=autolaunch:

RUN apt-get update \
 && apt-get install -y --no-install-recommends \
    # --- Chrome 必需依赖 ---
    ca-certificates \
    fonts-liberation \
    libasound2 \
    libatk-bridge2.0-0 \
    libatk1.0-0 \
    libc6 \
    libcairo2 \
    libcups2 \
    libdbus-1-3 \
    libexpat1 \
    libfontconfig1 \
    libgcc1 \
    libglib2.0-0 \
    libgtk-3-0 \
    libnspr4 \
    libnss3 \
    libpango-1.0-0 \
    libpangocairo-1.0-0 \
    libstdc++6 \
    libx11-6 \
    libx11-xcb1 \
    libxcb1 \
    libxcomposite1 \
    libxcursor1 \
    libxdamage1 \
    libxext6 \
    libxfixes3 \
    libxi6 \
    libxrandr2 \
    libxrender1 \
    libxss1 \
    libxtst6 \
    wget \
    xdg-utils \
    # ---- Puppeteer 常用字体 ----
    fonts-ipafont-gothic \
    fonts-wqy-zenhei \
    fonts-thai-tlwg \
    fonts-khmeros \
    fonts-kacst \
    fonts-freefont-ttf \
    dbus dbus-x11 \
 && rm -rf /var/lib/apt/lists/*

RUN groupadd -r pptruser && useradd -u $PPTRUSER_UID -rm -g pptruser -G audio,video pptruser
USER $PPTRUSER_UID
WORKDIR /home/pptruser

ENV PUPPETEER_USER_CHROME_DATA_DIR=/home/pptruser/chrome_data
ENV PUPPETEER_USER_QRCODE_IMG_DIR=/home/pptruser/qrcode_img

RUN mkdir -p $PUPPETEER_USER_CHROME_DATA_DIR $PUPPETEER_USER_QRCODE_IMG_DIR


#COPY deps/puppeteer-21.3.1.tgz ./
#RUN npm i ./puppeteer-21.3.1.tgz \
# && rm ./*.tgz

#USER root
#RUN PUPPETEER_CACHE_DIR=/home/pptruser/.cache/puppeteer \
#    npx puppeteer browsers install chrome --install-deps
#USER $PPTRUSER_UID

VOLUME ["/home/pptruser/chrome_data"]
VOLUME ["/home/pptruser/qrcode_img"]

# === 从这里开始集成你的代码 ===
COPY package*.json ./
RUN npm install --omit=dev
COPY src ./src

CMD ["node", "src/login.js"]
